// <auto-generated />
using ConsoleApp12.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DbconsoleProj.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    partial class ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.2");

            modelBuilder.Entity("ConsoleApp12.Models.Passanger", b =>
                {
                    b.Property<int>("IdPassanger")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Date_reg")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SurName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IdPassanger");

                    b.ToTable("Passangers");
                });

            modelBuilder.Entity("ConsoleApp12.Models.Point", b =>
                {
                    b.Property<int>("IdPoint")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Num")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IdPoint");

                    b.ToTable("Points");
                });

            modelBuilder.Entity("ConsoleApp12.Models.Ticket", b =>
                {
                    b.Property<int>("IdTicket")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Passanger")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("cost")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("departure_details")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("end_point")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("start_point")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IdTicket");

                    b.ToTable("Tickets");
                });
#pragma warning restore 612, 618
        }
    }
}
